### PR TITLE
Database Interfaces and Merged Layouts

### PR DESCRIPTION
**Pull request by krischer**
Hi all,

this PR significantly changes the internals of Instaseis and creates a new abstraction called "database interfaces" - this essentially encapsulates the I/O from the rest of the logic. In the future this should make it very easy to for example add the capability to use Instaseis to extract normal mode seismograms or similar endeavors.

This also contains proper implementations of the optimizations talked about in #35. The new database interfaces made it possible to implement all the various layouts and I hope this works for all affected parties.

With this PR, Instaseis has the following database interfaces:

* `BaseInstaseisDB`
* `BaseNetCDFInstaseisDB`
* `ReciprocalInstaseisDB`
* `ReciprocalMergedInstaseisDB`
* `ForwardInstaseisDB`
* `RemoteInstaseisDB`
* `SyngineInstaseisDB`

You'll notice that the tests now take a lot longer but I tried to deal with the additional complexity by just testing a lot more. The full test suite now requires `netcdf4`, `click`, and `pytest-xdist` to be installed. To run the tests in parallel:

```bash
$ cd /path/to/instaseis
$ py.test -n 4
```

Instaseis now also ships with a proper repacking script which is documented here (this also documents the new "Merged" database layout - please check if this works!):

https://www.geophysik.uni-muenchen.de/~krischer/instaseis_repack_doc/database_repacking.html

A merged database (best case) trades 125 single files reads against a single read which, especially on slow storage systems, should be MUCH faster (as seen in #35). Test with a small DB on an SSD which is kind of the worst case for the now optimizations to really show their worth:

```
tides_instaseis (598M): 40 s/sec
tides_instaseis_transposed_contiguous (1.2G): 52 s/sec
tides_instaseis_transposed_compressed (588M): 47 s/sec
tides_instaseis_merged_contiguous (1.7G): 240 s/sec
tides_instaseis_merged_compressed (869M): 200 s/sec
```

Note that the merged variant can now also be compressed which makes them quite a bit smaller but still very fast - this might be the optimal solution for syngine and similar things.

### CODE REVIEW

**Comment by sstaehler** [comment]
Very nice work, Lion!

One immediate question: What is with AxiSEM "moment" simulations, i.e. the much-neglected *forward* mode of Instaseis? Is that still supported? Can the new scheme handle it?

In MC Kernel, the order of fields in the 10D "MergedSnapshots" variable is:

1. MZZ: disp_s

**Comment by krischer** [comment]
That should very easy to add now that everything else is in place. I'll give it a shot. The default "moment" mode is still supported - the `ForwardInstaseisDB` interface does that.

**Comment by krischer** [comment]
Done. There is now also a `ForwardMergedInstaseisDB` interface and the repacking can do it as well. Documentation has also been updated: https://www.geophysik.uni-muenchen.de/~krischer/instaseis_repack_doc/database_repacking.html

I just used the order you proposed.

**Comment by alexhutko** [comment]
Hi Lion,

I’m not sure if this should go to the github or to you since I likely did a lot wrong, but here we go around the merry-go-round again.  I installed PR42 and converted some databases.  It looks like A) I get one error when running py.text -n 4, B) some databases saw a reduced size when using --compression_level 9, some did not  and C) I can’t test any of the databases for speed, i.e. it looks like it didn’t work?  I tried using the instaseis.scripts.compare_dbs, but couldn’t get that to work either. Error messages are below.

Any help is appreciated.  Thanks,
Alex


A) 

[product1@dpstage INSTASEIS_database_interfaces]$ py.test -n 4
/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/__init__.py:100: UserWarning: Please don't install from a tarball. Use the proper pypi release or install from git.
  "release or install from git.", UserWarning)
Creating transposed test database ...
Creating compressed re-transposed test database ...
Creating a simple repacked test database ...
Creating a simple transposed and repacked test database ...
Creating a merged test database ...
Creating a merged transposed test database ...
Creating a horizontal only merged test database ...
Creating a vertical only merged test database ...
================================================================================================================ test session starts =================================================================================================================
platform linux2 -- Python 2.7.12, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /products/SYNGINE_ALEX/INSTASEIS_database_interfaces, inifile: 
plugins: xdist-1.14
gw0 [964] / gw1 [964] / gw2 [964] / gw3 [964]
scheduling tests via LoadScheduling
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F..................................................................................................................................................................................................................................................................
====================================================================================================================== FAILURES ======================================================================================================================
__________________________________________________ test_phase_relative_offsets_multiple_stations[/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/tests/data/100s_db_bwd_strain_only] __________________________________________________
[gw1] linux2 -- Python 2.7.12 /home/product1/anaconda/bin/python
all_clients_all_callbacks = <instaseis.tests.tornado_testing_fixtures.AsyncClient object at 0x7f067044d950>

    def test_phase_relative_offsets_multiple_stations(all_clients_all_callbacks):
        client = all_clients_all_callbacks
    
        # Only for reciprocal ones as the depth is different otherwise...
        if not client.is_reciprocal:
            return
    
        db = instaseis.open_db(client.filepath, read_on_demand=True)
    
        # Now test multiple receiveers.
        # This is constructed in such a way that only one station will have a P
        # phase (due to the distance). So this is tested here.
        params = {
            "sourcelatitude": -39, "sourcelongitude": 20,
            "sourcedepthinmeters": 300000,
            "sourcemomenttensor": "100000,100000,100000,100000,100000,100000",
            "dt": 0.1, "format": "miniseed", "network": "IU,B*",
            "station": "ANT*,ANM?", "starttime": "P%2D10"}
        request = client.fetch(_assemble_url('seismograms', **params))
        assert request.code == 200
        st = obspy.read(request.buffer)
        assert len(st) == len(db.default_components)
    
        # This is constructed in such a way that only one station will have a P
        # phase (due to the distance). So this is tested here.
        params = {
            "sourcelatitude": -39, "sourcelongitude": 20,
            "sourcedepthinmeters": 300000,
            "sourcemomenttensor": "100000,100000,100000,100000,100000,100000",
            "dt": 0.1, "format": "miniseed", "network": "IU,B*",
            "station": "ANT*,ANM?", "endtime": "P%2D10"}
        request = client.fetch(_assemble_url('seismograms', **params))
        assert request.code == 200
        st = obspy.read(request.buffer)
        assert len(st) == len(db.default_components)
    
        # Now get both.
        params = {
            "sourcelatitude": 39, "sourcelongitude": 20,
            "sourcedepthinmeters": 300000,
            "sourcemomenttensor": "100000,100000,100000,100000,100000,100000",
            "dt": 0.1, "format": "miniseed", "network": "IU,B*",
            "station": "ANT*,ANM?", "starttime": "P%2D10"}
>       request = client.fetch(_assemble_url('seismograms', **params))

instaseis/tests/test_server.py:4278: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
instaseis/tests/tornado_testing_fixtures.py:69: in fetch
    return self.wait()
instaseis/tests/tornado_testing_fixtures.py:121: in wait
    self.__rethrow()
instaseis/tests/tornado_testing_fixtures.py:92: in __rethrow
    raise_exc_info(failure)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def timeout_func():
        try:
>           raise self.failureException(
                'Async operation timed out after %s seconds' %
                timeout)
E               AttributeError: 'AsyncClient' object has no attribute 'failureException'

instaseis/tests/tornado_testing_fixtures.py:102: AttributeError
======================================================================================================= 1 failed, 963 passed in 265.16 seconds =======================================================================================================
Deleting all test databases ...
[product1@dpstage INSTASEIS_database_interfaces]$ pwd
/products/SYNGINE_ALEX/INSTASEIS_database_interfaces

----------------------------------------------------------------------------
----------------------------------------------------------------------------
----------------------------------------------------------------------------


B)  It looks like ak135f_5s compressed, but the other two did not.
These are located in /gridftp_data/products/REPACK_TEST and can only be seen from dpstage.

599M prem_a_20s/
1.3G prem_a_20s_merge/
1.3G prem_a_20s_merge_compressed1/
1.3G prem_a_20s_merge_compressed9/
233M prem_a_20s_repack/

70G	prem_a_10s/
123G prem_a_10s_merge/
123G prem_a_10s_merge_compressed1/
123G prem_a_10s_merge_compressed9/

95G	ak135f_5s/
172G ak135f_5s_merge/
172G ak135f_5s_merge_compressed1/
99G	ak135f_5s_merge_compressed9/

----------------------------------------------------------------------------
----------------------------------------------------------------------------
----------------------------------------------------------------------------

C)  Testing works with the original databases, but not with any of the repacked ones.

[product1@dpstage REPACK_TEST]$ python -m instaseis.benchmark --pattern UnbufferedFullyRandom --time=10 /gridftp_data/products/REPACK_TEST/prem_a_10s_merge_compressed9
/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/__init__.py:100: UserWarning: Please don't install from a tarball. Use the proper pypi release or install from git.
  "release or install from git.", UserWarning)
===============================================================================
Instaseis Benchmark Suite

It enables to gauge the speed of Instaseis for a certain DB.
===============================================================================

It does not deal with OS level caches! So interpret the results accordingly!

ReciprocalInstaseisDB reciprocal Green's function Database (v8) generated with these parameters:
	components           : vertical and horizontal
	velocity model       : prem_ani
	attenuation          : True
	dominant period      : 10.000 s
	dump type            : displ_only
	excitation type      : dipole
	time step            : 2.441 s
	sampling rate        : 0.410 Hz
	number of samples    : 7376
	seismogram length    : 17999.6 s
	source time function : gauss_0
	source shift         : 17.084 s
	spatial order        : 4
	min/max radius       : 5671.0 - 6371.0 km
	Planet radius        : 6371.0 km
	min/max distance     : 0.0 - 180.0 deg
	time stepping scheme : symplec4
	compiler/user        : gfortran 5.2.0 by productext on dpstage
	directory/url        : ../../../gridftp_data/products/REPACK_TEST/prem_a_10s_merge_compressed9
	size of netCDF files : 122.2 GB
	generated by AxiSEM version v1.2-31-g69d4-dirty at 2015-11-12T09:36:02.000000Z

===============================================================================
Discovered 10 benchmark(s)
Pattern matching retained 1 benchmark(s)
===============================================================================


===============================================================================
===============================================================================


UnbufferedFullyRandom: Unbuffered, random src and receiver

	Time for initialization: 0.269540071487 sec
Traceback (most recent call last):
  File "/home/product1/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/product1/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/benchmark/__main__.py", line 433, in <module>
    benchmark.run()
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/benchmark/__main__.py", line 100, in run
    self.iterate()
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/benchmark/__main__.py", line 299, in iterate
    self.db.get_seismograms(source=src, receiver=rec)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/database_interfaces/base_instaseis_db.py", line 252, in get_seismograms
    components=components)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/database_interfaces/base_netcdf_instaseis_db.py", line 194, in _get_seismograms
    coordinates=coordinates, element_info=element_info)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/database_interfaces/reciprocal_instaseis_db.py", line 149, in _get_data
    ei.eltype, ei.axis, ei.xi, ei.eta)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces/instaseis/database_interfaces/base_netcdf_instaseis_db.py", line 209, in _get_strain_interp
    mesh_dict = mesh.f["Snapshots"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "/home/product1/anaconda/lib/python2.7/site-packages/h5py/_hl/group.py", line 164, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/home/ilan/minonda/conda-bld/work/h5py/h5o.c:3551)
KeyError: "Unable to open object (Object 'snapshots' doesn't exist)"
[product1@dpstage REPACK_TEST]$

**Comment by krischer** [comment]
Hi Alex,

thanks for the feedback - that's very helpful!

> A) I get one error when running py.test -n 4,

Should be fixed with one of the commits today - that happens on slowish systems especially when running tests in parallel. The timeout for the test server was just too small. Now it should be big enough.


> B) some databases saw a reduced size when using --compression_level 9, some did not and 
> C) I can’t test any of the databases for speed, i.e. it looks like it didn’t work? I tried using the instaseis.scripts.compare_dbs, but couldn’t get that to work either. Error messages are below.

* Compression level 9 is likely overkill as the data just does not compress very well. The zeros at the beginning compress well but these also compress at lower levels.
* It seems to me you used the repacking script in a way that I did not envision. How did you call it?

It should transform this:

```
tides_instaseis
├── PX
│   └── Data
│       └── ordered_output.nc4
└── PZ
    └── Data
        └── ordered_output.nc4
```

into this

```
tides_instaseis_merged_compressed
└── merged_output.nc4
```

And you call it be

```bash
$ python -m instaseis.scripts.repack_db tides_instaseis tides_instaseis_merged_compressed --method=merge --compression_level=4
```

For reference - what you have is:

```
├── prem_a_10s
│   ├── PX
│   │   └── Data
│   │       └── ordered_output.nc4
│   └── PZ
│       └── Data
│           └── ordered_output.nc4
├── prem_a_10s_merge
│   ├── PX
│   │   └── Data
│   │       └── merged_output.nc4
│   └── PZ
│       └── Data
│           └── merged_output.nc4
```

and the proper command:

```bash
$ python -m instaseis.scripts.repack_db prem_a_10s prem_a_10s_merge --method=merge --contiguous  # [replace with --compression_level=2 for compression]
```

I think you called it separately on each PX and PZ - I'll make sure Instaseis raises an error when trying to open such a database. I'll also make sure the documentation is better and clearer!

**Comment by alexhutko** [comment]
Thanks for the responses Lion.
Still some issues either with what I’m doing/interpreting or PR42, I can’t tell which….
Alex


A) py.test passes everthing w the updated PR42.
B) Still the same story, maybe I’m not running it correctly?

/home/product1/anaconda/bin/python $instaseisdir/scripts/repack_db.py --method=merge --compression_level 4 ./ak135f_5s ./ak135f_5s_merge_compressed4

95G	ak135f_5s/
122G	ak135f_5s_merge/
122G	ak135f_5s_merge_compressed1/
122G	ak135f_5s_merge_compressed2/
122G	ak135f_5s_merge_compressed4/

Transpose works.  Repack does not (see below)

C)  speed tests are now working, though we’ve been having serious I/O speed problems on our disk system so I don’t put too much weight into these results.  In general, the merged works faster than the original (about 2x) and the merge compressed works even faster (3-4x).

python -m instaseis.benchmark --pattern UnbufferedFullyRandom --time=40 /gridftp_data/products/REPACK_TEST/$model


————————
Trying to use method=repack
/home/product1/anaconda/bin/python $instaseisdir/scripts/repack_db.py --method=repack ./prem_a_20s ./prem_a_20s_repack

--> Processing file 1 of 2: ./prem_a_20s/PX/Data/ordered_output.nc4
	Copying 'Snapshots/disp_s' (1 of 3)...
	    [##----------------------------------]    6%  00:01:40
Traceback (most recent call last):
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces_Jul20/instaseis/scripts/repack_db.py", line 520, in <module>
    repack_database()
  File "/home/product1/anaconda/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/product1/anaconda/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/product1/anaconda/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/product1/anaconda/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces_Jul20/instaseis/scripts/repack_db.py", line 510, in repack_database
    compression_level=compression_level)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces_Jul20/instaseis/scripts/repack_db.py", line 54, in repack_file
    transpose=transpose)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces_Jul20/instaseis/scripts/repack_db.py", line 179, in recursive_copy
    transpose=transpose)
  File "/products/SYNGINE_ALEX/INSTASEIS_database_interfaces_Jul20/instaseis/scripts/repack_db.py", line 170, in recursive_copy
    src.variables[x.name][_s, :]
  File "netCDF4/_netCDF4.pyx", line 3634, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:37077)
  File "netCDF4/_netCDF4.pyx", line 4324, in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:46922)
IndexError

**Comment by krischer** [comment]
Hi Alex,


> A) py.test passes everthing w the updated PR42. 

Great :-)

> B) Still the same story, maybe I’m not running it correctly? 
/home/product1/anaconda/bin/python $instaseisdir/scripts/repack_db.py --method=merge --compression_level 4 ./ak135f_5s ./ak135f_5s_merge_compressed4 
95G ak135f_5s/ 
122G ak135f_5s_merge/ 
122G ak135f_5s_merge_compressed1/ 
122G ak135f_5s_merge_compressed2/ 
122G ak135f_5s_merge_compressed4/

You are running it correctly - the default value of `compression_level` is 2 so I think `ak135f_5s_merge/ ` and `ak135f_5s_merge_compressed2/ ` are exactly the same. To get an uncompressed version you have to pass the `--contiguous` flag.

Compression level 1 to 4 are very similar because the data just does not compress very well (floating point values). Many arrays have 0s at the beginning and these compress to almost nothing but that is already true at compression level 1, afterwards it is diminishing returns.



> Transpose works. Repack does not (see below)

True - Fixed in the latest commit.


I did some tests on your `productext` machine with the smallest database - the file system seems to be quite unstable right now as you mentioned so doing it with a bigger database would have been very tedious - the results are pretty much as expected:

```
599M	prem_a_20s
869M	prem_a_20s_merged_compressed_1
869M	prem_a_20s_merged_compressed_9
1.8G	prem_a_20s_merged_contiguous
583M	prem_a_20s_repack_compressed_2
590M	prem_a_20s_transposed_compressed_2
1.2G	prem_a_20s_transposed_contiguous
```

I cannot really benchmark as I don't have superuser rights and thus cannot clear the caches - not clearing the caches, especially for such a small database really really biases the results. The merged database should be at least an order of magnitude faster then the other layouts, especially for large databases and random accesses.

I did check that they all return the same seismograms on `productext`:

```bash
$ ../miniconda3/bin/python -m instaseis.scripts.compare_dbs prem_a*

======
prem_a_20s_merged_compressed_1 : True
prem_a_20s_merged_compressed_9 : True
prem_a_20s_merged_contiguous : True
prem_a_20s_repack_compressed_2 : True
prem_a_20s_transposed_compressed_2 : True
prem_a_20s_transposed_contiguous : True
======
```

I consider this to now work - I'm merging this because I can then merge the other outstanding pull request.

We can still use the thread to discuss the best possible database layout and general performance.

**Comment by alexhutko** [comment]
Hi Lion,

Manoch and I have done a lot of speed testing with various repacked databases.  Cache was dropped before every test.  I know earlier you mentioned UnbufferedFullyRandom was the best test and in this case, a method=merge + compress is the clear winner for database format, by a lot.  But under what I think may be more real world tests, the results don’t seem to justify larger volume repacked databases…

Can you think of a good test for us that hits syngine from multiple users, who likely have very non-random requests that likely will take advantage of cached results.

Thoughts (from anyone)?

Thanks,
Alex


  95 GB	ak135f_5s (original) 
122 GB	ak135f_5s_merge_compressed2
122 GB	ak135f_5s_merge_compressed8
  81 GB	ak135f_5s_repack
  82 GB	ak135f_5s_contigous
189 GB	ak135f_5s_merege_contigous

using instaseis.benchmark (time=45s, which seems stable)

--------- UnbufferedFullyRandom ----------
     ak135f_5s :
	1.06558 seismograms/sec
     ak135f_5s_merge_compressed2 :
	6.9687 seismograms/sec
     ak135f_5s_merge_compressed8 :
	6.35853 seismograms/sec
     ak135f_5s_repack :
	1.11642 seismograms/sec
     ak135f_5s_contigous :
	1.05318 seismograms/sec
     ak135f_5s_merege_contigous :
	9.07689 seismograms/sec

--------- BufferedHalfDegreeLatLngDepthScatter ----------
     ak135f_5s :
        84.1685 seismograms/sec
     ak135f_5s_merge_compressed2 :
        47.7568 seismograms/sec
     ak135f_5s_merge_compressed8 :
        47.6168 seismograms/sec
     ak135f_5s_repack :
        71.677 seismograms/sec
     ak135f_5s_contigous :
        94.7738 seismograms/sec
     ak135f_5s_merege_contigous :
        54.5239 seismograms/sec

--------- FiniteSourceEmulation ----------
     ak135f_5s :
        89.7662 seismograms/sec
     ak135f_5s_merge_compressed2 :
        118.254 seismograms/sec
     ak135f_5s_merge_compressed8 :
        111.064 seismograms/sec
     ak135f_5s_repack :
        90.6283 seismograms/sec
     ak135f_5s_contigous :
        89.6929 seismograms/sec
     ak135f_5s_merege_contigous :
        117.874 seismograms/sec


My own tests from within python using something like below.  I think they’re similar to yours.

db = instaseis.open_db(“MODEL”)
t0=time.time()
for Nsources...
   source = instaseis.FiniteSource.from_usgs_param_file(“Nepal.param”)
#   source = instaseis.Source(...
   for Nreceivers...
       receivers = instaseis.Receiver…
       tr_finite = db.get_seismograms_finite_source(source, receivers, components=('T'), dt=1.0)[0]
#       tr_finite = db.get_seismograms(source=source, receiver=receivers, components=('T'))[0]

Two different finite fault models to the same 30 GSN stations, Z & T components:

TOTAL time:  79.99070119857788 sec  prem_a_20s
TOTAL time:  78.5847156047821 sec  prem_a_20s_merge_compressed2
TOTAL time:  78.72317099571228 sec  prem_a_20s_merge_compressed8
TOTAL time:  83.71917080879211 sec  prem_a_20s_repack
TOTAL time:  81.7620530128479 sec  prem_a_20s_transpose
TOTAL time:  80.430340051651 sec  prem_a_20s_contigous
TOTAL time:  77.89400124549866 sec  prem_a_20s_merege_contigous
TOTAL time:  80.42214441299438 sec  prem_a_20s_repack_compress2
TOTAL time:  79.74637246131897 sec  prem_a_20s_transpose_compress2
TOTAL time:  74.52060985565186 sec  prem_a_20s_transpose_contiguous

What I consider a typical IRIS usage case- same 30 sources to same 100 GSN stations:

TOTAL time:  12.639808177947998 sec  prem_a_20s
TOTAL time:  16.149717569351196 sec  prem_a_20s_merge_compressed2
TOTAL time:  16.217032432556152 sec  prem_a_20s_merge_compressed8
TOTAL time:  12.670232772827148 sec  prem_a_20s_repack
TOTAL time:  12.813672304153442 sec  prem_a_20s_transpose
TOTAL time:  12.65830135345459 sec  prem_a_20s_contigous
TOTAL time:  16.27596688270569 sec  prem_a_20s_merege_contigous
TOTAL time:  12.472025156021118 sec  prem_a_20s_repack_compress2
TOTAL time:  12.81452751159668 sec  prem_a_20s_transpose_compress2
TOTAL time:  12.809259176254272 sec  prem_a_20s_transpose_contiguous
TOTAL time:  36.624571800231934 sec  prem_a_20s_repack_contiguous
TOTAL time:  30.992231845855713 sec  ak135f_5s
TOTAL time:  37.10445499420166 sec  ak135f_5s_merge_compressed2
TOTAL time:  37.9697368144989 sec  ak135f_5s_merge_compressed8
TOTAL time:  30.704602479934692 sec  ak135f_5s_repack
TOTAL time:  29.315311193466187 sec  ak135f_5s_contigous
TOTAL time:  36.37102675437927 sec  ak135f_5s_merege_contigous
TOTAL time:  49.257145404815674 sec  prem_a_10s
TOTAL time:  64.59827017784119 sec  prem_a_10s_merge_compressed2
TOTAL time:  60.56236219406128 sec  prem_a_10s_merge_compressed8
TOTAL time:  48.496063470840454 sec  prem_a_10s_repack
TOTAL time:  47.365795612335205 sec  prem_a_10s_contigous
TOTAL time:  71.00141549110413 sec  prem_a_10s_merege_contigous

**Comment by krischer** [comment]
Hi Alex,

this looks good. The results from the unbuffered random test looks pretty much as expected. The benefits of the merged layouts are most likely even larger for the 2s and the 1s database - about an order of magnitude faster.

The compressed 8 version is slower than the compressed 2 version because it likely takes more CPU time to uncompress it. The data does not compress very well so compression level 2 is IMHO the best choice.

I don't know which makes the most sense for syngine to be honest. But the compressed merged versions seems to be pretty good to me. ~7 times faster (for the worst case test) and only 30 % larger and I suspect the 2s databases should be even faster.

While this can only be answered with data once syngine has enough users I strongly suspect that the buffer/cache is actually not very important for syngine. In your tests you showed that they work really well for finite source models - the same is also true for the scatter test in the instaseis test suite. Once you have multiple concurrent users this already breaks down quite a bit.

I suspect a common use case for syngine will be to download data for a fixed set of stations but for multiple events - in that case the buffers are essentially never hit and the merged layout will thus deliver results about 10 times faster which is a lot.

Also multiple concurrent requests by multiple users will likely behave a bit like random requests so IMHO the "UnbufferedFullyRandom" benchmark is the only worthwhile scenario to optimize for.

But who knows - this are all just guesses. If I had to chose I would convert all databases to the merged layout (potentially compressed) and actually remove one or two databases if there is not enough space. The battle for the next time will be to get enough users for syngine so its existence can be justified - waiting 10 seconds or waiting <1 second (for a 2s database waveform) makes for a very different user experience and it thus might keep much more users around.

Cheers!

Lion

**Pull request merged**
